- name: Limpiar completamente configuración previa de Nginx y Gunicorn
  hosts: web
  become: true

  tasks:
    - name: Detener Gunicorn si está activo
      systemd:
        name: gunicorn
        state: stopped
      ignore_errors: yes

    - name: Eliminar servicio systemd de Gunicorn
      file:
        path: /etc/systemd/system/gunicorn.service
        state: absent

    - name: Eliminar sitios habilitados de Nginx
      file:
        path: /etc/nginx/sites-enabled
        state: absent

    - name: Recrear directorio limpio para sitios habilitados de Nginx
      file:
        path: /etc/nginx/sites-enabled
        state: directory
        mode: '0755'

    - name: Eliminar sitios disponibles de Nginx
      file:
        path: /etc/nginx/sites-available
        state: absent

    - name: Recrear directorio limpio para sitios disponibles de Nginx
      file:
        path: /etc/nginx/sites-available
        state: directory
        mode: '0755'

    - name: Recargar systemd después de eliminar Gunicorn
      systemd:
        daemon_reload: yes

    - name: Recargar Nginx para aplicar cambios
      service:
        name: nginx
        state: reloaded
