---
- name: Comprobar conexión a RDS
  hosts: web
  gather_facts: false
  tasks:
    - name: Instalar cliente psql
      apt:
        name: postgresql-client
        state: present
        update_cache: yes

    - name: Verificar conexión psql
      shell: |
        PGPASSWORD={{ lookup('env','DB_PASSWORD') }} \
        psql -h {{ lookup('env','RDS_ENDPOINT') }} \
             -U {{ lookup('env','DB_USER') }} \
             -d devpilotdb -c '\l'
      register: psql_check
      ignore_errors: yes

    - name: Mostrar resultado
      debug:
        msg: "{{ psql_check.stdout_lines }}"
