---
- name: Configurar EC2 para DevPilot (Flask + React)
  hosts: web
  become: true

  vars:
    app_root: /home/ubuntu/DevPilot
    backend_dir: "{{ app_root }}/Backend"
    frontend_dir: "{{ app_root }}/frontend"  # Corregido: era "Frontend" 
    venv_dir: "{{ backend_dir }}/venv"

  tasks:
    - name: Instalar paquetes del sistema
      apt:
        name:
          - python3-venv
          - python3-pip
          - git
          - nginx
          - nodejs
          - npm
        update_cache: yes
        state: latest

    - name: Eliminar directorio existente si hay problemas de permisos
      file:
        path: "{{ app_root }}"
        state: absent
      ignore_errors: yes

    - name: Clonar repositorio DevPilot
      git:
        repo: 'https://github.com/ProjectLabTeam2/DevPilot.git'
        dest: "{{ app_root }}"
        version: main
        force: yes
      become_user: ubuntu

    - name: Verificar estructura del proyecto
      shell: |
        echo "=== Contenido de {{ app_root }} ==="
        ls -la {{ app_root }}
        echo "=== Contenido de {{ backend_dir }} ==="
        ls -la {{ backend_dir }}
        echo "=== Verificando requirements.txt ==="
        cat {{ backend_dir }}/requirements.txt | head -10
      become_user: ubuntu
      register: project_structure

    - name: Mostrar estructura del proyecto
      debug:
        var: project_structure.stdout_lines

    - name: Crear virtualenv
      shell: |
        cd {{ backend_dir }}
        python3 -m venv venv
        echo "Virtual env creado exitosamente"
      become_user: ubuntu
      args:
        creates: "{{ venv_dir }}/bin/activate"

    - name: Instalar dependencias Python paso a paso
      shell: |
        cd {{ backend_dir }}
        . venv/bin/activate
        echo "=== Verificando Python en venv ==="
        which python
        python --version
        echo "=== Actualizando pip ==="
        pip install --upgrade pip
        echo "=== Instalando dependencias ==="
        pip install -r requirements.txt
        echo "=== Instalando Gunicorn ==="
        pip install gunicorn
        echo "=== Verificando Flask instalado ==="
        pip list | grep -i flask
        echo "=== Verificando comando flask ==="
        which flask || echo "Flask command not found"
        flask --version || echo "Flask version command failed"
      become_user: ubuntu
      register: pip_install_result

    - name: Mostrar resultado de instalación de dependencias
      debug:
        var: pip_install_result.stdout_lines

    - name: Copiar archivo .env al servidor
      copy:
        dest: "{{ backend_dir }}/.env"
        content: |
          FLASK_ENV=production
          SECRET_KEY={{ lookup('env','SECRET_KEY') }}
          JWT_SECRET_KEY={{ lookup('env','JWT_SECRET_KEY') }}
          DB_HOST={{ lookup('env','RDS_ENDPOINT') }}
          DB_USER={{ lookup('env','DB_USER') }}
          DB_PASSWORD={{ lookup('env','DB_PASSWORD') }}
          DB_NAME=devpilotdb
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Ejecutar flask db init
      shell: |
        cd {{ backend_dir }}
        {{ venv_dir }}/bin/python -m flask db init || echo "Ya existe migrations/"
      become_user: ubuntu
      args:
        executable: /bin/bash
      environment:
        FLASK_ENV: production
        FLASK_APP: run.py
        SECRET_KEY: "{{ lookup('env','SECRET_KEY') | default('dev-secret-key-change-in-production') }}"
        JWT_SECRET_KEY: "{{ lookup('env','JWT_SECRET_KEY') | default('dev-jwt-secret-change-in-production') }}"
        DB_HOST: "{{ lookup('env','RDS_ENDPOINT') | default('localhost') }}"
        DB_USER: "{{ lookup('env','DB_USER') | default('postgres') }}"
        DB_PASSWORD: "{{ lookup('env','DB_PASSWORD') | default('password') }}"
        DB_NAME: devpilotdb

    - name: Crear directorio migrations/versions si no existe
      file:
        path: "{{ backend_dir }}/migrations/versions"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      become_user: ubuntu

    - name: Ejecutar flask db migrate
      shell: |
        cd {{ backend_dir }}
        {{ venv_dir }}/bin/python -m flask db migrate -m "Initial migration"
      become_user: ubuntu
      args:
        executable: /bin/bash
      environment:
        FLASK_ENV: production
        FLASK_APP: run.py
        SECRET_KEY: "{{ lookup('env','SECRET_KEY') | default('dev-secret-key-change-in-production') }}"
        JWT_SECRET_KEY: "{{ lookup('env','JWT_SECRET_KEY') | default('dev-jwt-secret-change-in-production') }}"
        DB_HOST: "{{ lookup('env','RDS_ENDPOINT') | default('localhost') }}"
        DB_USER: "{{ lookup('env','DB_USER') | default('postgres') }}"
        DB_PASSWORD: "{{ lookup('env','DB_PASSWORD') | default('password') }}"
        DB_NAME: devpilotdb

    - name: Ejecutar flask db upgrade
      shell: |
        cd {{ backend_dir }}
        {{ venv_dir }}/bin/python -m flask db upgrade
      become_user: ubuntu
      args:
        executable: /bin/bash
      environment:
        FLASK_ENV: production
        FLASK_APP: run.py
        SECRET_KEY: "{{ lookup('env','SECRET_KEY') | default('dev-secret-key-change-in-production') }}"
        JWT_SECRET_KEY: "{{ lookup('env','JWT_SECRET_KEY') | default('dev-jwt-secret-key-change-in-production') }}"
        DB_HOST: "{{ lookup('env','RDS_ENDPOINT') | default('localhost') }}"
        DB_USER: "{{ lookup('env','DB_USER') | default('postgres') }}"
        DB_PASSWORD: "{{ lookup('env','DB_PASSWORD') | default('password') }}"
        DB_NAME: devpilotdb

    - name: Construir frontend con npm
      shell: |
        npm ci
        npm run build
      args:
        chdir: "{{ frontend_dir }}"
        creates: "{{ frontend_dir }}/dist"
      become_user: ubuntu

    - name: Configurar Nginx para servir la app
      copy:
        dest: /etc/nginx/sites-available/devpilot
        content: |
          server {
              listen 80;
              server_name _;

              root {{ frontend_dir }}/dist;
              index index.html;

              location /api/ {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
              }

              location / {
                  try_files $uri $uri/ /index.html;
              }
          }
      notify:
        - Enable Nginx site

    - name: Disable default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - Reload Nginx

    - name: Crear servicio systemd para Gunicorn
      copy:
        dest: /etc/systemd/system/gunicorn.service
        content: |
          [Unit]
          Description=Gunicorn for DevPilot
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory={{ backend_dir }}
          EnvironmentFile={{ backend_dir }}/.env
          ExecStart={{ venv_dir }}/bin/gunicorn --workers 3 --bind 127.0.0.1:5000 run:app
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd

  handlers:
    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/devpilot
        dest: /etc/nginx/sites-enabled/devpilot
        state: link

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Reload systemd
      systemd:
        daemon_reload: yes
        name: gunicorn
        state: restarted
        enabled: yes