---
- name: Configurar EC2 para DevPilot (Flask + React) con HTTPS
  hosts: web
  become: true

  vars:
    app_root: /home/ubuntu/DevPilot
    backend_dir: "{{ app_root }}/Backend"
    frontend_dir: "{{ app_root }}/frontend"
    venv_dir: "{{ backend_dir }}/venv"
    domain: "devpilot.online"
    email: "juanjogxmer0212@gmail.com" 

  tasks:
    - name: Instalar paquetes del sistema
      apt:
        name:
          - python3-venv
          - python3-pip
          - git
          - nginx
          - nodejs
          - npm
          - certbot
          - python3-certbot-nginx
        update_cache: yes
        state: latest

    - name: Eliminar directorio existente si hay problemas de permisos
      file:
        path: "{{ app_root }}"
        state: absent
      ignore_errors: yes

    - name: Clonar repositorio DevPilot
      git:
        repo: 'https://github.com/ProjectLabTeam2/DevPilot.git'
        dest: "{{ app_root }}"
        version: main
        force: yes
      become_user: ubuntu

    - name: Eliminar virtualenv si está corrupto
      file:
        path: "{{ venv_dir }}"
        state: absent
      ignore_errors: yes

    - name: Crear virtualenv
      shell: |
        cd "{{ backend_dir }}"
        python3 -m venv venv
      args:
        creates: "{{ venv_dir }}/bin/activate"
      become_user: ubuntu

    - name: Actualizar pip en el virtualenv
      pip:
        name: pip
        state: latest
        virtualenv: "{{ venv_dir }}"
      become_user: ubuntu

    - name: Instalar dependencias desde requirements.txt
      pip:
        requirements: "{{ backend_dir }}/requirements.txt"
        virtualenv: "{{ venv_dir }}"
      become_user: ubuntu

    - name: Instalar gunicorn en el virtualenv
      pip:
        name: gunicorn
        state: present
        virtualenv: "{{ venv_dir }}"
      become_user: ubuntu

    - name: Copiar archivo .env al servidor
      copy:
        dest: "{{ backend_dir }}/.env"
        content: |
          FLASK_ENV=production
          SECRET_KEY={{ lookup('env','SECRET_KEY') }}
          JWT_SECRET_KEY={{ lookup('env','JWT_SECRET_KEY') }}
          DB_HOST={{ lookup('env','RDS_ENDPOINT') }}
          DB_USER={{ lookup('env','DB_USER') }}
          DB_PASSWORD={{ lookup('env','DB_PASSWORD') }}
          DB_NAME=devpilotdb
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Ejecutar flask db upgrade
      shell: |
        cd "{{ backend_dir }}"
        "{{ venv_dir }}/bin/flask" db upgrade
      args:
        executable: /bin/bash
      become_user: ubuntu
      environment:
        FLASK_ENV: production
        FLASK_APP: run.py
        SECRET_KEY: "{{ lookup('env','SECRET_KEY') | default('dev-secret-key-change-in-production') }}"
        JWT_SECRET_KEY: "{{ lookup('env','JWT_SECRET_KEY') | default('dev-jwt-secret-change-in-production') }}"
        DB_HOST: "{{ lookup('env','RDS_ENDPOINT') | default('localhost') }}"
        DB_USER: "{{ lookup('env','DB_USER') | default('postgres') }}"
        DB_PASSWORD: "{{ lookup('env','DB_PASSWORD') | default('password') }}"
        DB_NAME: devpilotdb

    - name: Construir frontend con npm y vite
      shell: |
        npm install
        npx vite build
      args:
        chdir: "{{ frontend_dir }}"
        creates: "{{ frontend_dir }}/dist"
      become_user: ubuntu

    - name: Configurar Nginx para servir la app (HTTP, antes de obtener SSL)
      copy:
        dest: /etc/nginx/sites-available/devpilot
        content: |
          server {
              listen 80;
              server_name {{ domain }} www.{{ domain }};

              root {{ frontend_dir }}/dist;
              index index.html;

              location /api/ {
                  proxy_pass http://127.0.0.1:5512/api/;
                  proxy_http_version 1.1;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              location / {
                  try_files $uri /index.html;
              }

              error_page 404 /index.html;
          }
      notify:
        - Enable Nginx site

    - name: Disable default Nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify:
        - Reload Nginx

    - name: Asegurar permisos adecuados para el archivo .env
      file:
        path: "{{ backend_dir }}/.env"
        mode: '0644'
        owner: ubuntu
        group: ubuntu

    - name: Crear servicio systemd para Gunicorn
      copy:
        dest: /etc/systemd/system/gunicorn.service
        content: |
          [Unit]
          Description=Gunicorn for DevPilot
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory={{ backend_dir }}
          EnvironmentFile={{ backend_dir }}/.env
          ExecStart={{ venv_dir }}/bin/gunicorn -w 3 -b 127.0.0.1:5512 run:app
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify:
        - Reload systemd

    - name: Iniciar Gunicorn
      systemd:
        name: gunicorn
        state: started
        enabled: yes

    - name: Recargar Nginx tras configurar HTTP
      service:
        name: nginx
        state: reloaded

    - name: Esperar 5 segundos a que Nginx arranque
      wait_for:
        port: 80
        delay: 5

    - name: Obtener certificado SSL con Certbot
      command: >
        certbot certonly --nginx --non-interactive --agree-tos
        --email {{ email }}
        -d {{ domain }} -d www.{{ domain }}
      register: certbot_result
      failed_when: certbot_result.rc != 0 and "Certificate not yet due for renewal" not in certbot_result.stderr

    - name: Configurar Nginx para servir la app con HTTPS
      copy:
        dest: /etc/nginx/sites-available/devpilot
        content: |
          server {
              listen 80;
              server_name {{ domain }} www.{{ domain }};
              return 301 https://$host$request_uri;
          }

          server {
              listen 443 ssl;
              server_name {{ domain }} www.{{ domain }};

              ssl_certificate /etc/letsencrypt/live/{{ domain }}/fullchain.pem;
              ssl_certificate_key /etc/letsencrypt/live/{{ domain }}/privkey.pem;
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_prefer_server_ciphers on;
              ssl_ciphers HIGH:!aNULL:!MD5;

              root {{ frontend_dir }}/dist;
              index index.html;

              location /api/ {
                  proxy_pass http://127.0.0.1:5512/api/;
                  proxy_http_version 1.1;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              location / {
                  try_files $uri /index.html;
              }

              error_page 404 /index.html;
          }
      notify:
        - Reload Nginx

    - name: Recargar Nginx tras configurar HTTPS
      service:
        name: nginx
        state: reloaded

    - name: Configurar renovación automática de certificados
      cron:
        name: "Renovación automática Let's Encrypt"
        job: "certbot renew --quiet --nginx"
        minute: "0"
        hour: "3"

  handlers:
    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/devpilot
        dest: /etc/nginx/sites-enabled/devpilot
        state: link

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Reload systemd
      systemd:
        daemon_reload: yes
        name: gunicorn
        state: restarted
        enabled: yes
